const MOVIEDB_API_URL = process.env.MOVIEDB_API_URL;
const MOVIEDB_API_KEY_V3 = process.env.MOVIEDB_API_KEY_V3;
const MOVIEDB_IMAGE_URL = process.env.NEXT_PUBLIC_MOVIEDB_IMAGE_URL;

export {MOVIEDB_API_URL, MOVIEDB_API_KEY_V3, MOVIEDB_IMAGE_URL};
